spring:
  application:
    name: banking-system

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:bankingdb
    driver-class-name:
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.eomaxl.bankapplication: DEBUG
    org.springframework.security: DEBUG